### ISSUE TITLE
apk zip ka password kya hai

### ISSUE THREAD

**Issue by kapilsharma-gts** [akashmishra242/WhatsApp_clone#2]
????

**Comment by akashmishra242** [comment]
I have put on the password in the zip file because some of the features/APIs have a quota in it, so to restrict overuse/misuse of the app I have password-protected it.

If you are a learner, I think you should fork the repository and run the build command of your own to get the .apk file.
If you still require it, mail me with the appropriate reason for the use.
email: [akashmishra242@gmail.com](akashmishra242@gmail.com)

closing the issue.
Regards,
Akash
