### ISSUE TITLE
import 'package:whatsapp_clone/constants.dart' as c; 

### ISSUE THREAD

**Issue by Cevocey** [akashmishra242/WhatsApp_clone#3]
where is the constants.dart file???
i cant see

**Comment by akashmishra242** [comment]
hello Cevocey,
I intentionally did not upload the constant.dart file as it contains my public API's and other auth keys/tokens that can be misused.
so, I suggest you to create a constant.dart file by yourself and put the necessary keys/tokens that are ever required.

Regard,
Akash

**Comment by AnTheez** [comment]
can you add this without our keys & tokens?
pls

**Comment by akashmishra242** [comment]
Hello AnTheez, 

The constant.dart contains the necessary keys/tokens that are:

**APP_CERTIFICATE :** your app certificate which you will get from 'Agora' for the video calling feature.
**APP_ID** :  your app id which you will get from 'Agora' for the video calling feature.
**base_url** : the base URL on which you want to send a request for video calling.

I am attaching a screenshot as well in order to tell you what the file looks like. 
![WhatsApp Image 2023-04-26 at 21 11 28](https://github.com/akashmishra242/WhatsApp_clone/assets/91900783/0f10e9e2-b830-4ed6-8181-67aee2cd9989)


Regard,
Akash

**Comment by AnTheez** [comment]
[image: image.png]

пт, 12 мая 2023 г. в 20:26, Akash Mishra ***@***.***>:

**Comment by AnTheez** [comment]
thanks for the help with the constants, it helped me a lot, now I'm doing
my graduation project, every minute counts...

Can you please suggest what kind of indexes should be added and how?[image:
image.png]
[image: image.png]
[image: image.png]

пт, 12 мая 2023 г. в 20:29, Андрій Шапошников ***@***.***>:

**Comment by akashmishra242** [comment]
I can't see any of the images which you have attached.
kindly attach the images correctly and preview them before posting a comment.

Do the needful for me to assist you further.

regards,
Akash
